### ISSUE TITLE
An error occurred after installation

### ISSUE THREAD

**Issue by helloshaohua** [nuxt-modules/mdc#183]
```text
 ERROR  Cannot find module './emojis'
Require stack:
- /Users/wushaohua/workspace/vue/hello.com/emojilib

  Require stack:
  - emojilib
  at Module._resolveFilename (node:internal/modules/cjs/loader:1140:15)
  at Module._load (node:internal/modules/cjs/loader:981:27)
  at Module.require (node:internal/modules/cjs/loader:1231:19)
  at require (node:internal/modules/helpers:177:18)
  at emojilib:2:8
  at ViteNodeRunner.runModule (node_modules/.pnpm/vite-node@1.5.0_sass@1.75.0/node_modules/vite-node/dist/client.mjs:362:11)
  at ViteNodeRunner.directRequest (node_modules/.pnpm/vite-node@1.5.0_sass@1.75.0/node_modules/vite-node/dist/client.mjs:346:16)
  at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
  at async ViteNodeRunner.cachedRequest (node_modules/.pnpm/vite-node@1.5.0_sass@1.75.0/node_modules/vite-node/dist/client.mjs:189:14)
  at async ViteNodeRunner.dependencyRequest (node_modules/.pnpm/vite-node@1.5.0_sass@1.75.0/node_modules/vite-node/dist/client.mjs:233:12)
```

**Comment by farnabaz** [comment]
Do you mind creating a simple reproduction?

**Comment by gtwww** [comment]
@Atinux @farnabaz  also encountered this issue, and it can be resolved by wrapping the code with <ClientOnly>.

dependencies:
@nuxt/image 1.7.0
@nuxt/ui 2.16.0
@nuxtjs/mdc 0.7.0
nuxt 3.11.2
vue 3.4.27
vue-router 4.3.2
zod 3.23.8

devDependencies:
@iconify-json/ri 1.1.20
@iconify-json/solar 1.1.9

**Comment by imlautaro** [comment]
Same thing happened to me, I solved it by adding .client.vue to my component but as they said previously, not the final/ideal solution.

**Comment by RihanArfan** [comment]
Fixed it by creating `.npmrc` with `shamefully-hoist=true` content.

Without shamfully hoisting, making the page .client.vue also worked for me. Wrapping with <ClientOnly> didn't seem to work though, which I found odd but I didn't debug further.

**Comment by senhuaa** [comment]
I had this problem for a few days, and I found a solution.
```pnpm
pnpm add remark-emoji
```
then
```ts
//nuxt.config.ts
mdc: {
    remarkPlugins: {
      emoji: {
        src: 'remark-emoji'
      }
    }
  },
```
