### ISSUE TITLE
Import error while install nuxt/content with nuxtjs/mdc

### ISSUE THREAD

**Issue by dkhoperiya** [nuxt-modules/mdc#202]
Hi!

I'm trying to add nuxt/content to existing project and catch error:

`
[nitro] [unhandledRejection] TypeError: Expected node, got `[object Object]`
    at assertNode (file:///Users/dkhoperiya/platform_test/node_modules/unified/lib/index.js:1258:11)
    at Function.run (file:///Users/dkhoperiya/platform_test/node_modules/unified/lib/index.js:874:5)
    at executor (file:///Users/dkhoperiya/platform_test/node_modules/unified/lib/index.js:737:12)
    at new Promise (<anonymous>)
    at Function.process (file:///Users/dkhoperiya/platform_test/node_modules/unified/lib/index.js:720:47)
    at <anonymous> (/Users/dkhoperiya/platform_test/node_modules/@nuxtjs/mdc/dist/runtime/parser/index.mjs:72:43)
`

nuxt/content latest
unified latest

When i try to downgrade unifide to major 10 version it starts to work, but with some errors later. 

Any ideas?

**Comment by farnabaz** [comment]
This is a generic error and could have many reasons. It might happen because of a conflict between some plugin or unsupported syntax in one of your files.
If you could find which file causes this issue and share the content, we can find the cause much faster.
