### ISSUE TITLE
0.9.1: failed to resolve import "#components" when building

### ISSUE THREAD

**Issue by binaryoverload** [nuxt-modules/mdc#264]
With the new [v0.9.1](https://github.com/nuxt-modules/mdc/releases/tag/v0.9.1) release, a [change was made](https://github.com/nuxt-modules/mdc/commit/45ce8abe6dbceb9529e111ded87c355f9cb88ece) to introduce the following code

https://github.com/nuxt-modules/mdc/blob/53a79fba2d5c40c7a697bb60f50ccdb8680f505d/src/module.ts#L170-L173

When building the project (`npm run build`) with `@nuxt/image` installed, this causes an error:

```bash
ERROR  Nuxt Build Error: [vite]: Rollup failed to resolve import "#components" from "virtual:nuxt:/home/projects/llqiwmjjoy.github/.nuxt/mdc-image-component.mjs".
This is most likely unintended because it can break your application at runtime.
If you do want to externalize this module explicitly add it to
build.rollupOptions.external

  This is most likely unintended because it can break your application at runtime.
  If you do want to externalize this module explicitly add it to
  build.rollupOptions.external
  at viteWarn (node_modules/vite/dist/node/chunks/dep-Cyk9bIUq.js:65627:17)
  at onRollupWarning (node_modules/vite/dist/node/chunks/dep-Cyk9bIUq.js:65659:5)
  at onwarn (node_modules/vite/dist/node/chunks/dep-Cyk9bIUq.js:65322:7)
  at eval (node_modules/rollup/dist/es/shared/node-entry.js:19418:13)
  at Object.logger (node_modules/rollup/dist/es/shared/node-entry.js:21144:9)
  at ModuleLoader.handleInvalidResolvedId (node_modules/rollup/dist/es/shared/node-entry.js:20033:26)
  at eval (node_modules/rollup/dist/es/shared/node-entry.js:19991:26)
```

I have replicated this issue in a brand new project: 
- https://stackblitz.com/edit/github-xvcl5u?file=nuxt.config.ts&view=editor
- Run `npm run build` to see the error

**Comment by adamdehaven** [comment]
🤔 your reproduction actually worked fine for me.

If you're still having the issue locally, you can likely resolve this by running the [`prepare` command](https://nuxt.com/docs/api/commands/prepare) before `build`.

If I run `npm run nuxt prepare && npm run build` everything works as expected.
