### ISSUE TITLE
ERROR  Cannot find module './compose/composer.js'

### ISSUE THREAD

**Issue by cikomesi** [nuxt-modules/mdc#313]
I try the min example to get error :

+ node: 22.11.0
+ pnpm: 9.14.2

nuxt.config.ts
```
// https://nuxt.com/docs/api/configuration/nuxt-config
export default defineNuxtConfig({
    compatibilityDate: '2024-11-01',
    // future: { compatibilityVersion: 4 },
    devtools: {enabled: true},
    modules: ['@nuxtjs/mdc']
})
```

package.json
```
{
  "name": "nuxt-app",
  "private": true,
  "type": "module",
  "scripts": {
    "build": "nuxt build",
    "dev": "nuxt dev",
    "generate": "nuxt generate",
    "preview": "nuxt preview",
    "postinstall": "nuxt prepare"
  },
  "dependencies": {
    "@nuxtjs/mdc": "^0.11.1",
    "nuxt": "^3.14.1592",
    "vue": "latest",
    "vue-router": "latest"
  },
  "packageManager": "pnpm@9.14.2+sha512.6e2baf77d06b9362294152c851c4f278ede37ab1eba3a55fda317a4a17b209f4dbb973fb250a77abc463a341fcb1f17f17cfa24091c4eb319cda0d9b84278387"
}

```

app.vue
```
<template>
  <div>
    <NuxtPage/>
  </div>
</template>

```

pages/index
```
<script setup lang="ts">
const md = `# Welcome to docs4.dev`
</script>

<template>
  121
  <MDC :value="md" />
</template>

<style scoped>

</style>
```

when i run dev:

![Image](https://github.com/user-attachments/assets/8de671c6-cf3b-40e6-8515-a3fefaa64d7d)

console

```
Nuxt 3.14.1592 with Nitro 2.10.4                                                                              03:40:01
                                                                                                              03:40:01
  ➜ Local:    http://localhost:3000/
  ➜ Network:  use --host to expose

  ➜ DevTools: press Shift + Alt + D in the browser (v1.6.4)                                                                                                                                     03:40:04

√ Vite client built in 34ms                                                                                                                                                                     03:40:05
√ Vite server built in 464ms                                                                                                                                                                    03:40:05
√ Nuxt Nitro server built in 695 ms                                                                                                                                                       nitro 03:40:06
i Vite client warmed up in 0ms                                                                                                                                                                  03:40:06  
i Vite server warmed up in 488ms                                                                                                                                                                03:40:07

 WARN  [Vue Router warn]: uncaught error during route navigation:


 ERROR  Cannot find module './compose/composer.js'
Require stack:
- C:\Users\vpt94\Desktop\nuxt3_mdc_starter\yaml

  Require stack:
  - yaml
  at Function._resolveFilename (node:internal/modules/cjs/loader:1249:15)
  at Function._load (node:internal/modules/cjs/loader:1075:27)
  at TracingChannel.traceSync (node:diagnostics_channel:315:14)
  at wrapModuleLoad (node:internal/modules/cjs/loader:218:24)
  at Module.require (node:internal/modules/cjs/loader:1340:12)
  at require (node:internal/modules/helpers:141:16)
  at yaml:3:16
  at ViteNodeRunner.runModule (/C:/Users/vpt94/Desktop/nuxt3_mdc_starter/node_modules/.pnpm/vite-node@2.1.8_@types+node@22.10.2_terser@5.37.0/node_modules/vite-node/dist/client.mjs:399:11)
  at ViteNodeRunner.directRequest (/C:/Users/vpt94/Desktop/nuxt3_mdc_starter/node_modules/.pnpm/vite-node@2.1.8_@types+node@22.10.2_terser@5.37.0/node_modules/vite-node/dist/client.mjs:381:16)
  at process.processTicksAndRejections (node:internal/process/task_queues:105:5)


 WARN  [Vue Router warn]: uncaught error during route navigation:


 ERROR  Cannot find module './compose/composer.js'
Require stack:
- C:\Users\vpt94\Desktop\nuxt3_mdc_starter\yaml

  Require stack:
  - yaml
  at Function._resolveFilename (node:internal/modules/cjs/loader:1249:15)
  at Function._load (node:internal/modules/cjs/loader:1075:27)
  at TracingChannel.traceSync (node:diagnostics_channel:315:14)
  at wrapModuleLoad (node:internal/modules/cjs/loader:218:24)
  at Module.require (node:internal/modules/cjs/loader:1340:12)
  at require (node:internal/modules/helpers:141:16)
  at yaml:3:16
  at ViteNodeRunner.runModule (/C:/Users/vpt94/Desktop/nuxt3_mdc_starter/node_modules/.pnpm/vite-node@2.1.8_@types+node@22.10.2_terser@5.37.0/node_modules/vite-node/dist/client.mjs:399:11)
  at ViteNodeRunner.directRequest (/C:/Users/vpt94/Desktop/nuxt3_mdc_starter/node_modules/.pnpm/vite-node@2.1.8_@types+node@22.10.2_terser@5.37.0/node_modules/vite-node/dist/client.mjs:381:16)
  at process.processTicksAndRejections (node:internal/process/task_queues:105:5)


 WARN  [nuxt] Failed to stringify dev server logs. Received DevalueError: Cannot stringify arbitrary non-POJOs. You can define your own reducer/reviver for rich types following the instructions in https://nuxt.com/docs/api/composables/use-nuxt-app#payload.


 WARN  [Vue Router warn]: uncaught error during route navigation:


 ERROR  Cannot find module './compose/composer.js'
Require stack:
- C:\Users\vpt94\Desktop\nuxt3_mdc_starter\yaml

  Require stack:
  - yaml
  at Function._resolveFilename (node:internal/modules/cjs/loader:1249:15)
  at Function._load (node:internal/modules/cjs/loader:1075:27)
  at TracingChannel.traceSync (node:diagnostics_channel:315:14)
  at wrapModuleLoad (node:internal/modules/cjs/loader:218:24)
  at Module.require (node:internal/modules/cjs/loader:1340:12)
  at require (node:internal/modules/helpers:141:16)
  at yaml:3:16
  at ViteNodeRunner.runModule (/C:/Users/vpt94/Desktop/nuxt3_mdc_starter/node_modules/.pnpm/vite-node@2.1.8_@types+node@22.10.2_terser@5.37.0/node_modules/vite-node/dist/client.mjs:399:11)
  at ViteNodeRunner.directRequest (/C:/Users/vpt94/Desktop/nuxt3_mdc_starter/node_modules/.pnpm/vite-node@2.1.8_@types+node@22.10.2_terser@5.37.0/node_modules/vite-node/dist/client.mjs:381:16)
  at process.processTicksAndRejections (node:internal/process/task_queues:105:5)


 WARN  [Vue Router warn]: uncaught error during route navigation:


 ERROR  Cannot find module './compose/composer.js'
Require stack:
- C:\Users\vpt94\Desktop\nuxt3_mdc_starter\yaml

  Require stack:
  - yaml
  at Function._resolveFilename (node:internal/modules/cjs/loader:1249:15)
  at Function._load (node:internal/modules/cjs/loader:1075:27)
  at TracingChannel.traceSync (node:diagnostics_channel:315:14)
  at wrapModuleLoad (node:internal/modules/cjs/loader:218:24)
  at Module.require (node:internal/modules/cjs/loader:1340:12)
  at require (node:internal/modules/helpers:141:16)
  at yaml:3:16
  at ViteNodeRunner.runModule (/C:/Users/vpt94/Desktop/nuxt3_mdc_starter/node_modules/.pnpm/vite-node@2.1.8_@types+node@22.10.2_terser@5.37.0/node_modules/vite-node/dist/client.mjs:399:11)
  at ViteNodeRunner.directRequest (/C:/Users/vpt94/Desktop/nuxt3_mdc_starter/node_modules/.pnpm/vite-node@2.1.8_@types+node@22.10.2_terser@5.37.0/node_modules/vite-node/dist/client.mjs:381:16)
  at process.processTicksAndRejections (node:internal/process/task_queues:105:5)


 WARN  [Vue Router warn]: uncaught error during route navigation:


 ERROR  Cannot find module './compose/composer.js'
Require stack:
- C:\Users\vpt94\Desktop\nuxt3_mdc_starter\yaml

  Require stack:
  - yaml
  at Function._resolveFilename (node:internal/modules/cjs/loader:1249:15)
  at Function._load (node:internal/modules/cjs/loader:1075:27)
  at TracingChannel.traceSync (node:diagnostics_channel:315:14)
  at wrapModuleLoad (node:internal/modules/cjs/loader:218:24)
  at Module.require (node:internal/modules/cjs/loader:1340:12)
  at require (node:internal/modules/helpers:141:16)
  at yaml:3:16
  at ViteNodeRunner.runModule (/C:/Users/vpt94/Desktop/nuxt3_mdc_starter/node_modules/.pnpm/vite-node@2.1.8_@types+node@22.10.2_terser@5.37.0/node_modules/vite-node/dist/client.mjs:399:11)
  at ViteNodeRunner.directRequest (/C:/Users/vpt94/Desktop/nuxt3_mdc_starter/node_modules/.pnpm/vite-node@2.1.8_@types+node@22.10.2_terser@5.37.0/node_modules/vite-node/dist/client.mjs:381:16)
  at process.processTicksAndRejections (node:internal/process/task_queues:105:5)


 WARN  [nuxt] Failed to stringify dev server logs. Received DevalueError: Cannot stringify arbitrary non-POJOs. You can define your own reducer/reviver for rich types following the instructions in https://nuxt.com/docs/api/composables/use-nuxt-app#payload.

i hmr update /app.vue                                                                                                                                                                           03:40:27
i nuxt.config.ts updated. Restarting Nuxt...                                                                                                                                                    03:40:27  

 ERROR  [unhandledRejection] Nuxt instance is unavailable!                                                                                                                                      03:40:27  

  at useNuxt (/C:/Users/vpt94/Desktop/nuxt3_mdc_starter/node_modules/.pnpm/@nuxt+kit@3.14.1592_magicast@0.3.5_rollup@4.28.1/node_modules/@nuxt/kit/dist/index.mjs:36:11)
  at normalizeTemplate (/C:/Users/vpt94/Desktop/nuxt3_mdc_starter/node_modules/.pnpm/@nuxt+kit@3.14.1592_magicast@0.3.5_rollup@4.28.1/node_modules/@nuxt/kit/dist/index.mjs:2988:18)
  at /C:/Users/vpt94/Desktop/nuxt3_mdc_starter/node_modules/.pnpm/nuxt@3.14.1592_@parcel+watcher@2.5.0_@types+node@22.10.2_ioredis@5.4.1_magicast@0.3.5_rollup@_vmij26jpp3svejxf3uaxjaoc7m/node_modules/nuxt/dist/index.mjs:5439:47
  at Array.map (<anonymous>)
  at generateApp (/C:/Users/vpt94/Desktop/nuxt3_mdc_starter/node_modules/.pnpm/nuxt@3.14.1592_@parcel+watcher@2.5.0_@types+node@22.10.2_ioredis@5.4.1_magicast@0.3.5_rollup@_vmij26jpp3svejxf3uaxjaoc7m/node_modules/nuxt/dist/index.mjs:5439:33)
  at async _applyPromised (/C:/Users/vpt94/Desktop/nuxt3_mdc_starter/node_modules/.pnpm/perfect-debounce@1.0.0/node_modules/perfect-debounce/dist/index.mjs:54:10)


 ERROR  [unhandledRejection] Nuxt instance is unavailable!                                                                                                                                      03:40:27  

  at useNuxt (/C:/Users/vpt94/Desktop/nuxt3_mdc_starter/node_modules/.pnpm/@nuxt+kit@3.14.1592_magicast@0.3.5_rollup@4.28.1/node_modules/@nuxt/kit/dist/index.mjs:36:11)
  at normalizeTemplate (/C:/Users/vpt94/Desktop/nuxt3_mdc_starter/node_modules/.pnpm/@nuxt+kit@3.14.1592_magicast@0.3.5_rollup@4.28.1/node_modules/@nuxt/kit/dist/index.mjs:2988:18)
  at /C:/Users/vpt94/Desktop/nuxt3_mdc_starter/node_modules/.pnpm/nuxt@3.14.1592_@parcel+watcher@2.5.0_@types+node@22.10.2_ioredis@5.4.1_magicast@0.3.5_rollup@_vmij26jpp3svejxf3uaxjaoc7m/node_modules/nuxt/dist/index.mjs:5439:47
  at Array.map (<anonymous>)
  at generateApp (/C:/Users/vpt94/Desktop/nuxt3_mdc_starter/node_modules/.pnpm/nuxt@3.14.1592_@parcel+watcher@2.5.0_@types+node@22.10.2_ioredis@5.4.1_magicast@0.3.5_rollup@_vmij26jpp3svejxf3uaxjaoc7m/node_modules/nuxt/dist/index.mjs:5439:33)
  at async _applyPromised (/C:/Users/vpt94/Desktop/nuxt3_mdc_starter/node_modules/.pnpm/perfect-debounce@1.0.0/node_modules/perfect-debounce/dist/index.mjs:54:10)


 ERROR  [unhandledRejection] Nuxt instance is unavailable!                                                                                                                                      03:40:27  

  at useNuxt (/C:/Users/vpt94/Desktop/nuxt3_mdc_starter/node_modules/.pnpm/@nuxt+kit@3.14.1592_magicast@0.3.5_rollup@4.28.1/node_modules/@nuxt/kit/dist/index.mjs:36:11)
  at normalizeTemplate (/C:/Users/vpt94/Desktop/nuxt3_mdc_starter/node_modules/.pnpm/@nuxt+kit@3.14.1592_magicast@0.3.5_rollup@4.28.1/node_modules/@nuxt/kit/dist/index.mjs:2988:18)
  at /C:/Users/vpt94/Desktop/nuxt3_mdc_starter/node_modules/.pnpm/nuxt@3.14.1592_@parcel+watcher@2.5.0_@types+node@22.10.2_ioredis@5.4.1_magicast@0.3.5_rollup@_vmij26jpp3svejxf3uaxjaoc7m/node_modules/nuxt/dist/index.mjs:5439:47
  at Array.map (<anonymous>)
  at generateApp (/C:/Users/vpt94/Desktop/nuxt3_mdc_starter/node_modules/.pnpm/nuxt@3.14.1592_@parcel+watcher@2.5.0_@types+node@22.10.2_ioredis@5.4.1_magicast@0.3.5_rollup@_vmij26jpp3svejxf3uaxjaoc7m/node_modules/nuxt/dist/index.mjs:5439:33)
  at async _applyPromised (/C:/Users/vpt94/Desktop/nuxt3_mdc_starter/node_modules/.pnpm/perfect-debounce@1.0.0/node_modules/perfect-debounce/dist/index.mjs:54:10)

  ➜ DevTools: press Shift + Alt + D in the browser (v1.6.4)                                                                                                                                     03:40:27

√ Vite client built in 20ms                                                                                                                                                                     03:40:28
√ Vite server built in 315ms                                                                                                                                                                    03:40:28
√ Nuxt Nitro server built in 620 ms                                                                                                                                                       nitro 03:40:29
i Vite client warmed up in 0ms                                                                                                                                                                  03:40:29  
i Vite server warmed up in 423ms                                                                                                                                                                03:40:29

[03:40:37]  WARN  'manifest-route-rule' middleware already exists at 'C:/Users/vpt94/Desktop/nuxt3_mdc_starter/node_modules/.pnpm/nuxt@3.14.1592_@parcel+watcher@2.5.0_@types+node@22.10.2_ioredis@5.4.1_magicast@0.3.5_rollup@_vmij26jpp3svejxf3uaxjaoc7m/node_modules/nuxt/dist/app/middleware/manifest-route-rule.js'. You can set override: true to replace it.

√ Vite server hmr 6 files in 369.768ms

[03:41:10]  WARN  'manifest-route-rule' middleware already exists at 'C:/Users/vpt94/Desktop/nuxt3_mdc_starter/node_modules/.pnpm/nuxt@3.14.1592_@parcel+watcher@2.5.0_@types+node@22.10.2_ioredis@5.4.1_magicast@0.3.5_rollup@_vmij26jpp3svejxf3uaxjaoc7m/node_modules/nuxt/dist/app/middleware/manifest-route-rule.js'. You can set override: true to replace it.

√ Vite server hmr 9 files in 11.94ms

 WARN  [Vue Router warn]: uncaught error during route navigation:


 ERROR  Cannot find module './compose/composer.js'
Require stack:
- C:\Users\vpt94\Desktop\nuxt3_mdc_starter\yaml

  Require stack:
  - yaml
  at Function._resolveFilename (node:internal/modules/cjs/loader:1249:15)
  at Function._load (node:internal/modules/cjs/loader:1075:27)
  at TracingChannel.traceSync (node:diagnostics_channel:315:14)
  at wrapModuleLoad (node:internal/modules/cjs/loader:218:24)
  at Module.require (node:internal/modules/cjs/loader:1340:12)
  at require (node:internal/modules/helpers:141:16)
  at yaml:3:16
  at ViteNodeRunner.runModule (/C:/Users/vpt94/Desktop/nuxt3_mdc_starter/node_modules/.pnpm/vite-node@2.1.8_@types+node@22.10.2_terser@5.37.0/node_modules/vite-node/dist/client.mjs:399:11)
  at ViteNodeRunner.directRequest (/C:/Users/vpt94/Desktop/nuxt3_mdc_starter/node_modules/.pnpm/vite-node@2.1.8_@types+node@22.10.2_terser@5.37.0/node_modules/vite-node/dist/client.mjs:381:16)
  at process.processTicksAndRejections (node:internal/process/task_queues:105:5)


 WARN  [Vue Router warn]: uncaught error during route navigation:


 ERROR  Cannot find module './compose/composer.js'
Require stack:
- C:\Users\vpt94\Desktop\nuxt3_mdc_starter\yaml

  Require stack:
  - yaml
  at Function._resolveFilename (node:internal/modules/cjs/loader:1249:15)
  at Function._load (node:internal/modules/cjs/loader:1075:27)
  at TracingChannel.traceSync (node:diagnostics_channel:315:14)
  at wrapModuleLoad (node:internal/modules/cjs/loader:218:24)
  at Module.require (node:internal/modules/cjs/loader:1340:12)
  at require (node:internal/modules/helpers:141:16)
  at yaml:3:16
  at ViteNodeRunner.runModule (/C:/Users/vpt94/Desktop/nuxt3_mdc_starter/node_modules/.pnpm/vite-node@2.1.8_@types+node@22.10.2_terser@5.37.0/node_modules/vite-node/dist/client.mjs:399:11)
  at ViteNodeRunner.directRequest (/C:/Users/vpt94/Desktop/nuxt3_mdc_starter/node_modules/.pnpm/vite-node@2.1.8_@types+node@22.10.2_terser@5.37.0/node_modules/vite-node/dist/client.mjs:381:16)
  at process.processTicksAndRejections (node:internal/process/task_queues:105:5)


 WARN  [nuxt] Failed to stringify dev server logs. Received DevalueError: Cannot stringify arbitrary non-POJOs. You can define your own reducer/reviver for rich types following the instructions in https://nuxt.com/docs/api/composables/use-nuxt-app#payload.

i hmr update /pages/index.vue                                                                                                                                                                   03:45:35

[03:45:35]  WARN  'manifest-route-rule' middleware already exists at 'C:/Users/vpt94/Desktop/nuxt3_mdc_starter/node_modules/.pnpm/nuxt@3.14.1592_@parcel+watcher@2.5.0_@types+node@22.10.2_ioredis@5.4.1_magicast@0.3.5_rollup@_vmij26jpp3svejxf3uaxjaoc7m/node_modules/nuxt/dist/app/middleware/manifest-route-rule.js'. You can set override: true to replace it.

√ Vite server hmr 9 files in 16.804ms

 WARN  [Vue Router warn]: uncaught error during route navigation:


 ERROR  Cannot find module './compose/composer.js'
Require stack:
- C:\Users\vpt94\Desktop\nuxt3_mdc_starter\yaml

  Require stack:
  - yaml
  at Function._resolveFilename (node:internal/modules/cjs/loader:1249:15)
  at Function._load (node:internal/modules/cjs/loader:1075:27)
  at TracingChannel.traceSync (node:diagnostics_channel:315:14)
  at wrapModuleLoad (node:internal/modules/cjs/loader:218:24)
  at Module.require (node:internal/modules/cjs/loader:1340:12)
  at require (node:internal/modules/helpers:141:16)
  at yaml:3:16
  at ViteNodeRunner.runModule (/C:/Users/vpt94/Desktop/nuxt3_mdc_starter/node_modules/.pnpm/vite-node@2.1.8_@types+node@22.10.2_terser@5.37.0/node_modules/vite-node/dist/client.mjs:399:11)
  at ViteNodeRunner.directRequest (/C:/Users/vpt94/Desktop/nuxt3_mdc_starter/node_modules/.pnpm/vite-node@2.1.8_@types+node@22.10.2_terser@5.37.0/node_modules/vite-node/dist/client.mjs:381:16)
  at process.processTicksAndRejections (node:internal/process/task_queues:105:5)


 WARN  [Vue Router warn]: uncaught error during route navigation:


 ERROR  Cannot find module './compose/composer.js'
Require stack:
- C:\Users\vpt94\Desktop\nuxt3_mdc_starter\yaml

  Require stack:
  - yaml
  at Function._resolveFilename (node:internal/modules/cjs/loader:1249:15)
  at Function._load (node:internal/modules/cjs/loader:1075:27)
  at TracingChannel.traceSync (node:diagnostics_channel:315:14)
  at wrapModuleLoad (node:internal/modules/cjs/loader:218:24)
  at Module.require (node:internal/modules/cjs/loader:1340:12)
  at require (node:internal/modules/helpers:141:16)
  at yaml:3:16
  at ViteNodeRunner.runModule (/C:/Users/vpt94/Desktop/nuxt3_mdc_starter/node_modules/.pnpm/vite-node@2.1.8_@types+node@22.10.2_terser@5.37.0/node_modules/vite-node/dist/client.mjs:399:11)
  at ViteNodeRunner.directRequest (/C:/Users/vpt94/Desktop/nuxt3_mdc_starter/node_modules/.pnpm/vite-node@2.1.8_@types+node@22.10.2_terser@5.37.0/node_modules/vite-node/dist/client.mjs:381:16)
  at process.processTicksAndRejections (node:internal/process/task_queues:105:5)


 WARN  [nuxt] Failed to stringify dev server logs. Received DevalueError: Cannot stringify arbitrary non-POJOs. You can define your own reducer/reviver for rich types following the instructions in https://nuxt.com/docs/api/composables/use-nuxt-app#payload.



```

**Comment by cikomesi** [comment]
nuxt-content also find this error:

https://github.com/nuxt/content/issues/2918

**Comment by farnabaz** [comment]
Unfortunately, the module does not work well without `shamefully-hoist`.

Add `shamefully-hoist=true` into the `.npmrc` file in the project root and re-installing the dependencies. It will solve the issue
